### ISSUE TITLE
Support for Sublime Text 3

### ISSUE THREAD

**Issue by sparkyfen** [bigluck/alfred2-sublimeprojects#1]
Enhancement request:
The session file is located at `~/Library/Application Support/Sublime Text 3/Local/Session.sublime_session`

Not sure if it's possible to add a sublime text 3 option!

Thanks!

**Comment by bigluck** [comment]
Hi @brutalhonesty , I couldn't test this workflow with Sublime Text 3 yet.
I don't known if the new plist file use the same tree structure of the previous version.

Try to edit the sublime.php file (open Alfred > Workflow, right click on the "Sublime Text 2 Projects" > Show in finder and then open the sublime.php script).

**Comment by sparkyfen** [comment]
Just imported into Alfred and I'm running Sublime Text 3, good to go, no changes needed! Thanks! :D
