### ISSUE TITLE
Can't open project

### ISSUE THREAD

**Issue by agektmr** [bigluck/alfred2-sublimeprojects#3]
Hi,

Thanks for awesome workflow!  
I have installed this workflow couple days back. I saw it working on that day but can't do similar today and yesterday and wondering how I can debug it.

On terminal, `which subl` works and `subl -a --project "project_name"` works without any problem. Typing `subproject_name` gives me right result on Alfred as well. But typing `return` there won't do anything.

Do you have any idea what is going wrong?

**Comment by bigluck** [comment]
I'm sorry @agektmr but I really don't know.
By default this plugin invoke a `subl -n --project "{query}"`, and {query} is the project file path.
If you type `cmd+return` will be invoked a `subl -a --project "{query}"`

**Comment by JustinAiken** [comment]
@agektmr, try putting what `which subl` gives you directly in the workflow instead of just `subl` - for some reason launching `subl` from the bash script in the plugin didn't work for me, but launching `/usr/local/bin/subl` did... probably because my .bashrc is empty and .zshrc has all the proper paths...

**Comment by jolantis** [comment]
@JustinAiken thanks for the tip. The workflow wasn't working for me neither, but after putting the path that `which subl` gives me in the workflow (e.g. `/usr/local/bin/subl` instead of just `subl`) it's working like a charm.

@bigluck thanks for this great workflow.

**Comment by agektmr** [comment]
Thanks guys for the solution. I'll check it and configure. I recommend @bigluck to mention about this somewhere. Closing issue now.
